### ISSUE TITLE
Submodule?

### ISSUE THREAD

**Issue by StevenACoffman** [nordicdyno/golang-tools#2]
What do you think about putting a submodule in the `_tools` directory? This would still make the root go.mod file independent of the tool dependencies, but allow you to lock tool versions (linters, etc.)

**Comment by nordicdyno** [comment]
I don't like git submodules and I don't know much people who does. IMO: git submodules hard to manage and they are source of unpredictable pain.

**Comment by StevenACoffman** [comment]
Actually, I didn't mean a **git** submodule (yuck!). I meant putting a `go.mod` into the root directory, and a `go.mod` into the `_tools` directory, making a **go** submodule, not a git one.
